update kusion spec model
KusionStack/konfig pull request #29
Opened 2022-08-17 10:49 UTC by markliby

#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [x] N
- [ ] Y 

#### 2. What is the scope of this PR (e.g. component or file name):

appops/
base/

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Other

update kusion spec model, add type field

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [x] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [ ] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [x] Other

#### 6. Release note

Please refer to [Release Notes Language Style Guide](https://kusionstack.io/docs/governance/release-policy/) to write a quality release note.

```release-note
None
```

2022-08-17 11:09 UTC, howieyuen requested changes

2022-08-17 11:09 UTC, howieyuen commented on base/pkg/kusion_models/kube/mixins/output_type_mixin.k
>                  "mode" = "managed"
delete this line

2022-08-17 11:25 UTC, howieyuen approved these changes
lgtm

2022-08-22 03:08 UTC, elliotxx approved these changes
lgtm

2022-08-22 03:50 UTC, merged