Dev/peefy/upgrade kcl code
KusionStack/konfig pull request #8
Opened 2022-05-24 10:41 UTC by Peefy

Purpose:
1. upgrade kcl code
2. bump kclvm expected version to v0.4.2

2022-05-25 08:59 UTC, howieyuen requested changes

2022-05-25 08:59 UTC, howieyuen commented on appops/nginx-example/dev/ci-test/stdout.golden.yaml
> -id: apps/v1:Deployment:nginx-example:nginx-exampledev
changes should not appears here. the newest version of kusion is equal to `kcl compile`

2022-05-26 10:29 UTC, Peefy commented on base/pkg/kusion_models/kube/backend/job_backend.k
> +# Frontend volume to kubernetes volume mapping.
The latest version of KCL may not support forward references to global variables like this:
````
schema A:
    b: int = a

a = 1
````
So change it to
````
a = 1
schema A:
    b: int = a
````

2022-05-26 10:31 UTC, Peefy commented on appops/nginx-example/dev/ci-test/stdout.golden.yaml
> -id: apps/v1:Deployment:nginx-example:nginx-exampledev
I do use the latest version of kusion compile, attributes will show up at the top, but it doesn't affect Config CI tests

2022-05-27 06:30 UTC, howieyuen commented
please squash commits to be compatible with purpose of this PR.

2022-08-11 07:21 UTC, closed without merging